# Generated by Django 5.1.15 on 2026-02-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('etapa', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Qualificação'), ('PROPOSTA', 'Proposta'), ('NEGOCIACAO', 'Negociação'), ('FECHAMENTO', 'Fechamento'), ('PERDIDA', 'Perdida')], default='PROSPECCAO', max_length=12, verbose_name='Etapa')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor estimado')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGACAO', 'Ligação'), ('EMAIL', 'E-mail'), ('REUNIAO', 'Reunião'), ('WHATSAPP', 'WhatsApp'), ('VISITA', 'Visita')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interacoes', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='sales.oportunidade', verbose_name='Oportunidade')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
