# Generated by Django 6.0.2 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_meta_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='data_follow_up',
            field=models.DateField(blank=True, help_text='Data prevista para o próximo contato', null=True, verbose_name='Data do follow-up'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='proxima_acao',
            field=models.CharField(blank=True, default='', help_text='Descreva brevemente a próxima ação a ser realizada', max_length=200, verbose_name='Próxima ação'),
        ),
    ]
