# Generated by Django 5.1.15 on 2026-02-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_follow_up_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('PRECO', 'Preço'), ('PRAZO', 'Prazo'), ('CONCORRENCIA', 'Concorrência'), ('DESISTENCIA', 'Desistência'), ('SEM_RETORNO', 'Sem retorno'), ('OUTRO', 'Outro')], default='', max_length=13, verbose_name='Motivo da perda'),
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(blank=True, choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Qualificação'), ('PROPOSTA', 'Proposta'), ('NEGOCIACAO', 'Negociação'), ('FECHAMENTO', 'Fechamento'), ('PERDIDA', 'Perdida')], default='', max_length=12, verbose_name='Etapa anterior')),
                ('etapa_nova', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Qualificação'), ('PROPOSTA', 'Proposta'), ('NEGOCIACAO', 'Negociação'), ('FECHAMENTO', 'Fechamento'), ('PERDIDA', 'Perdida')], max_length=12, verbose_name='Etapa nova')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, verbose_name='Data da mudança')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='sales.oportunidade', verbose_name='Oportunidade')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Históricos de Etapa',
                'ordering': ['data_mudanca'],
            },
        ),
    ]
