# Generated by Django 5.1.15 on 2026-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GESTOR', 'Gestor Comercial'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=10, verbose_name='Papel'),
        ),
    ]
