# Generated by Django 5.1.15 on 2026-02-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfil_papel'),
        ('core', '0002_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gestor',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__papel': 'GESTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to=settings.AUTH_USER_MODEL, verbose_name='Gestor'),
        ),
    ]
