# Generated by Django 5.1.15 on 2026-02-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_empresa_perfil_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
    ]
