# Generated by Django 5.1.15 on 2026-02-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('empresa', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('origem', models.CharField(max_length=100, verbose_name='Origem')),
                ('produto_interesse', models.CharField(blank=True, default='', max_length=200, verbose_name='Produto de interesse')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_CONTATO', 'Em contato'), ('AGUARDANDO', 'Aguardando'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('convertido_em', models.DateTimeField(blank=True, null=True, verbose_name='Convertido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
