# Generated by Django 5.1.15 on 2026-02-14 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGACAO', 'Ligação'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('EMAIL', 'E-mail')], max_length=11, verbose_name='Tipo de contato')),
                ('resultado', models.CharField(choices=[('NAO_ATENDEU', 'Não atendeu'), ('SEM_INTERESSE', 'Sem interesse'), ('PEDIU_RETORNO', 'Pediu retorno'), ('INTERESSADO', 'Interessado'), ('FECHOU', 'Fechou')], max_length=14, verbose_name='Resultado')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('data_contato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do contato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='prospeccao.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Contato do Lead',
                'verbose_name_plural': 'Contatos do Lead',
                'ordering': ['-data_contato'],
            },
        ),
    ]
