# Generated by Django 5.1.15 on 2026-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_contato',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_contato_principal',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Contato principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_contato',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do contato'),
        ),
    ]
