# Generated by Django 6.0.2 on 2026-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_cnpj_cpf_cliente_email_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_ultimo_contato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contato'),
        ),
    ]
