# Generated by Django 6.0.2 on 2026-02-22 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_cliente_data_ultimo_contato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGACAO', 'Ligação'), ('EMAIL', 'E-mail'), ('REUNIAO', 'Reunião'), ('WHATSAPP', 'WhatsApp'), ('VISITA', 'Visita')], max_length=10, verbose_name='Tipo de contato')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('proxima_acao_em', models.DateField(blank=True, null=True, verbose_name='Próxima ação em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_carteira', to='crm.cliente', verbose_name='Cliente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_carteira_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Contato da Carteira',
                'verbose_name_plural': 'Contatos da Carteira',
                'ordering': ['-criado_em'],
            },
        ),
    ]
